export default {
  'assets/images/bmw/bmw5SeriesModel.png': require('../assets/images/bmw/bmw5SeriesModel.png'),
  'assets/images/bmw/bmw6SeriesModel.png': require('../assets/images/bmw/bmw6SeriesModel.png'),
  'assets/images/bmw/bmwxSeriesModel.png': require('../assets/images/bmw/bmwxSeriesModel.png'),
  'assets/images/hyundai/genesis.png': require('../assets/images/hyundai/genesis.png'),
  'assets/images/hyundai/elantra.png': require('../assets/images/hyundai/elantra.png'),
  'assets/images/hyundai/veloster.png': require('../assets/images/hyundai/veloster.png'),
  'assets/images/tesla/Model3.png': require('../assets/images/tesla/Model3.png'),
  'assets/images/tesla/ModelS.png': require('../assets/images/tesla/ModelS.png'),
  'assets/images/tesla/ModelX.png': require('../assets/images/tesla/ModelX.png'),
  'assets/images/mercedes/MercedesGClass.png': require('../assets/images/mercedes/MercedesGClass.png'),
  // import all other images
  company: require('../assets/images/company.png'),
  retailer: require('../assets/images/retailer.png'),
  individual: require('../assets/images/individual.png'),
  business: require('../assets/images/business-icon.png'),
  job: require('../assets/images/job.png'),
  transmissionType: require('../assets/images/featureIcon-1.png'),
  color: require('../assets/images/featureIcon-2.png'),
  wheel: require('../assets/images/featureIcon-3.png'),
  cabOver: require('../assets/images/featureIcon-4.png'),
  seats: require('../assets/images/featureIcon-5.png'),
  meter: require('../assets/images/featureIcon-6.png'),
  borrower: require('../assets/images/borrower.png'),
  
};
